#!/bin/sh
#!/bin/bash
# simple Bash Menu Script by jackluke

printf "Monterey beta setup assistant autologinfix by jackluke"

printf "\n\n\n"

echo "Welcome to Monterey beta setup assistant autologinfix"
echo "\nBased on the ASentientBot auto login for non metal workaround"
touch /private/var/db/.AppleSetupDone
echo "\nYou can close with CMD+Q or modify from login options selecting auto login"
open /System/Library/PreferencePanes/Accounts.prefPane
/System/Library/CoreServices/Setup\ Assistant.app/Contents/MacOS/Setup\ Assistant1